version: '2'

volumes:
  postgres_data:
    driver: local

services:
  jm-app:
    container_name: product-app
    image: app
#    build:
#      context: ./
#      dockerfile: Dockerfile
    ports:
      - "8020:8020"
    depends_on:
      - jm-postgres

  jm-postgres:
    container_name: product-postgress
    image: postgres:10.1
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=product_market
    volumes:
      - "postgres_data:/var/lib/postgresql/data"